2024-10-30 18:07:45,360 ERROR: Exception on /schoolyearperiods/ [GET] [in C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py:825]
Traceback (most recent call last):
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_cors\extension.py", line 194, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
                                                ^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 865, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask\app.py", line 1239, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\desktop\Desktop\gspFinance\gspfinanceback\app.py", line 26, in initialize_db
    if db.connection is None:  # Only connect if not already connected
       ^^^^^^^^^^^^^
  File "C:\Users\desktop\AppData\Local\Programs\Python\Python312\Lib\site-packages\flask_mongoengine\__init__.py", line 138, in connection
    return current_app.extensions["mongoengine"][self]["conn"]
           ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'mongoengine'
2024-10-30 18:10:03,024 INFO: GSP Finance Backend Startup [in C:\Users\desktop\Desktop\gspFinance\gspfinanceback\app.py:33]
